version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: upwork
      MYSQL_USER: upwork
      MYSQL_PASSWORD: upwork
      MYSQL_TCP_PORT: 8010
    restart: always
  server:
    image: tomcat:9.0
    volumes:
      - "./target/authentication-service.war:/usr/local/tomcat/webapps/authentication-service.war"
    depends_on:
      - database
    restart: always
  nginx:
    build:
      context: ./nginx
    depends_on:
      - database
      - server
    ports:
      - "8000:80"
    restart: always